filter:
    excluded_paths:
        - 'vendor/*'
        - 'web/*'
    paths: {  }
checks:
    php:
        code_rating: true
        duplication: true
tools:
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_cs_fixer:
        config:
            level: psr2
            fixers:
                indentation: true
                trailing_spaces: true
                phpdoc_params: true
                braces: true
    php_analyzer: true
    php_cpd: true
    php_sim: true
    php_mess_detector: true
    php_pdepend: true
    external_code_coverage:
        timeout: 600 # Timeout in seconds.

changetracking:
    bug_patterns:
        - '\bfix(?:es|ed)?\b'
    feature_patterns:
        - '\badd(?:s|ed)?\b'
        - '\bimplement(?:s|ed)?\b'
before_commands: {  }
after_commands: {  }
artifacts: {  }